//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Linq.Expressions;
using System.Runtime.Serialization;
using ReactiveUI;
using System.Reactive.Linq;
using System.Reflection;

namespace Faccts.Model.Entities
{
    public partial class HearingIssue : INotifyComplexPropertyChanging, IReactiveNotifyPropertyChanged
    {
    
    	private MakeObjectReactiveHelper _reactiveHelper;
    	public HearingIssue()
    	{
    		_reactiveHelper = new MakeObjectReactiveHelper(this);
    		Initialize();
    		Observable.Merge<Object>(
    				this.ObservableForProperty(x => x.PermanentRO)
    				,this.ObservableForProperty(x => x.ChildCustodyOrChildVisitation)
    				,this.ObservableForProperty(x => x.ChildSupport)
    				,this.ObservableForProperty(x => x.SpousalSupport)
    				,this.ObservableForProperty(x => x.IsOtherIssue)
    				,this.ObservableForProperty(x => x.OtheIssueText)
    			).
    			Subscribe(_ =>
    			{
    				IsDirty = true;
    			}
    			);
    	}
    
    	partial void Initialize();
    	
    	private bool _isDirty;
    	public bool IsDirty
    	{
    		get
    		{
    			return _isDirty;
    		}
    		set
    		{
    			if (_isDirty == value)
    				return;
    			OnPropertyChanging("IsDirty");
    			_isDirty = value;
    			OnPropertyChanged("IsDirty");
    		}
    	}
    
    	public IObservable<IObservedChange<object, object>> Changed 
    	{
    		get { return _reactiveHelper.Changed; }
    	}
    	public IObservable<IObservedChange<object, object>> Changing 
    	{
    		get { return _reactiveHelper.Changing; }
    	}
    	public IDisposable SuppressChangeNotifications() 
    	{
    		return _reactiveHelper.SuppressChangeNotifications();
    	}
    
    	private PropertyChangingEventHandler _propertyChanging;
    	public event PropertyChangingEventHandler PropertyChanging
    	{
    		add { _propertyChanging += value; }
    		remove {_propertyChanging -= value; }
    	}
        #region Simple Properties
    
        [DataMember]
        public bool PermanentRO
        {
            get { return _permanentRO; }
            set
            {
                if (_permanentRO != value)
                {
                    OnComplexPropertyChanging();
    				OnPropertyChanging("PermanentRO");
                    _permanentRO = value;
                    OnPropertyChanged("PermanentRO");
                }
            }
        }
        private bool _permanentRO;
    
        [DataMember]
        public bool ChildCustodyOrChildVisitation
        {
            get { return _childCustodyOrChildVisitation; }
            set
            {
                if (_childCustodyOrChildVisitation != value)
                {
                    OnComplexPropertyChanging();
    				OnPropertyChanging("ChildCustodyOrChildVisitation");
                    _childCustodyOrChildVisitation = value;
                    OnPropertyChanged("ChildCustodyOrChildVisitation");
                }
            }
        }
        private bool _childCustodyOrChildVisitation;
    
        [DataMember]
        public bool ChildSupport
        {
            get { return _childSupport; }
            set
            {
                if (_childSupport != value)
                {
                    OnComplexPropertyChanging();
    				OnPropertyChanging("ChildSupport");
                    _childSupport = value;
                    OnPropertyChanged("ChildSupport");
                }
            }
        }
        private bool _childSupport;
    
        [DataMember]
        public bool SpousalSupport
        {
            get { return _spousalSupport; }
            set
            {
                if (_spousalSupport != value)
                {
                    OnComplexPropertyChanging();
    				OnPropertyChanging("SpousalSupport");
                    _spousalSupport = value;
                    OnPropertyChanged("SpousalSupport");
                }
            }
        }
        private bool _spousalSupport;
    
        [DataMember]
        public bool IsOtherIssue
        {
            get { return _isOtherIssue; }
            set
            {
                if (_isOtherIssue != value)
                {
                    OnComplexPropertyChanging();
    				OnPropertyChanging("IsOtherIssue");
                    _isOtherIssue = value;
                    OnPropertyChanged("IsOtherIssue");
                }
            }
        }
        private bool _isOtherIssue;
    
        [DataMember]
        public string OtheIssueText
        {
            get { return _otheIssueText; }
            set
            {
                if (_otheIssueText != value)
                {
                    OnComplexPropertyChanging();
    				OnPropertyChanging("OtheIssueText");
                    _otheIssueText = value;
                    OnPropertyChanged("OtheIssueText");
                }
            }
        }
        private string _otheIssueText;

        #endregion

        #region ChangeTracking
    
        private void OnComplexPropertyChanging()
        {
            if (_complexPropertyChanging != null)
            {
                _complexPropertyChanging(this, new EventArgs());
            }
        }
    
        event EventHandler INotifyComplexPropertyChanging.ComplexPropertyChanging { add { _complexPropertyChanging += value; } remove { _complexPropertyChanging -= value; } }
        private event EventHandler _complexPropertyChanging;
    
        private void OnPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
    	private void OnPropertyChanging(String propertyName)
        {
            if (_propertyChanging != null)
            {
                _propertyChanging(this, new PropertyChangingEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged { add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
    
        public static void RecordComplexOriginalValues(String parentPropertyName, HearingIssue complexObject, ObjectChangeTracker changeTracker)
        {
            if (String.IsNullOrEmpty(parentPropertyName))
            {
                throw new ArgumentException("String parameter cannot be null or empty.", "parentPropertyName");
            }
    
            if (changeTracker == null)
            {
                throw new ArgumentNullException("changeTracker");
            }
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.PermanentRO", parentPropertyName), complexObject == null ? null : (object)complexObject.PermanentRO);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.ChildCustodyOrChildVisitation", parentPropertyName), complexObject == null ? null : (object)complexObject.ChildCustodyOrChildVisitation);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.ChildSupport", parentPropertyName), complexObject == null ? null : (object)complexObject.ChildSupport);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.SpousalSupport", parentPropertyName), complexObject == null ? null : (object)complexObject.SpousalSupport);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.IsOtherIssue", parentPropertyName), complexObject == null ? null : (object)complexObject.IsOtherIssue);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.OtheIssueText", parentPropertyName), complexObject == null ? null : (object)complexObject.OtheIssueText);
        }

        #endregion

    }
}
