//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Linq.Expressions;
using System.Runtime.Serialization;
using ReactiveUI;

namespace Faccts.Model.Entities
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Applications))]
    [KnownType(typeof(Users))]
    public partial class Memberships: IObjectWithChangeTracker, IReactiveNotifyPropertyChanged, INavigationPropertiesLoadable
    {
    		
    		private MakeObjectReactiveHelper _reactiveHelper;
    
    		public Memberships()
    		{
    			_reactiveHelper = new MakeObjectReactiveHelper(this);
    			Initialize();
    		}
    
    		partial void Initialize();
    		
    
    		public IObservable<IObservedChange<object, object>> Changed 
    		{
    			get { return _reactiveHelper.Changed; }
    		}
    		public IObservable<IObservedChange<object, object>> Changing 
    		{
    			get { return _reactiveHelper.Changing; }
    		}
    		public IDisposable SuppressChangeNotifications() 
    		{
    			return _reactiveHelper.SuppressChangeNotifications();
    		}
    
    		private PropertyChangingEventHandler _propertyChanging;
    		public event PropertyChangingEventHandler PropertyChanging
    		{
    			add
    			{
    				_propertyChanging += value;
    			}
    			remove
    			{
    				_propertyChanging -= value;
    			}
    		}
    
    		public event EventHandler<LoadingNavigationPropertiesEventArgs> OnNavigationPropertyLoading;
    		protected virtual void RaiseNavigationPropertyLoading(string propertyName)
            {
                if (OnNavigationPropertyLoading != null)
                    OnNavigationPropertyLoading(this, new LoadingNavigationPropertiesEventArgs(propertyName));
            }
    
            protected virtual void RaiseNavigationPropertyLoading<T>(Expression<Func<T>> propertyExpression)
            {
                var body = propertyExpression.Body as MemberExpression;
                if (body == null)
                    throw new ArgumentException("'propertyExpression' should be a member expression");
    
                var expression = body.Expression as ConstantExpression;
                if (expression == null)
                    throw new ArgumentException("'propertyExpression' body should be a constant expression");
    
                object target = Expression.Lambda(expression).Compile().DynamicInvoke();
    
                RaiseNavigationPropertyLoading(body.Member.Name);
            }
    	    #region Simple Properties
    
        [DataMember]
        public System.Guid UserId
        {
            get { return _userId; }
            set
            {
                if (_userId != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'UserId' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    if (!IsDeserializing)
                    {
                        if (Users != null && Users.UserId != value)
                        {
                            Users = null;
                        }
                    }
    				OnPropertyChanging("UserId");
                    _userId = value;
                    OnPropertyChanged("UserId");
                }
            }
        }
        private System.Guid _userId;
    
        [DataMember]
        public System.Guid ApplicationId
        {
            get { return _applicationId; }
            set
            {
                if (_applicationId != value)
                {
                    ChangeTracker.RecordOriginalValue("ApplicationId", _applicationId);
                    if (!IsDeserializing)
                    {
                        if (Applications != null && Applications.ApplicationId != value)
                        {
                            Applications = null;
                        }
                    }
    				OnPropertyChanging("ApplicationId");
                    _applicationId = value;
                    OnPropertyChanged("ApplicationId");
                }
            }
        }
        private System.Guid _applicationId;
    
        [DataMember]
        public string Password
        {
            get { return _password; }
            set
            {
                if (_password != value)
                {
    				OnPropertyChanging("Password");
                    _password = value;
                    OnPropertyChanged("Password");
                }
            }
        }
        private string _password;
    
        [DataMember]
        public int PasswordFormat
        {
            get { return _passwordFormat; }
            set
            {
                if (_passwordFormat != value)
                {
    				OnPropertyChanging("PasswordFormat");
                    _passwordFormat = value;
                    OnPropertyChanged("PasswordFormat");
                }
            }
        }
        private int _passwordFormat;
    
        [DataMember]
        public string PasswordSalt
        {
            get { return _passwordSalt; }
            set
            {
                if (_passwordSalt != value)
                {
    				OnPropertyChanging("PasswordSalt");
                    _passwordSalt = value;
                    OnPropertyChanged("PasswordSalt");
                }
            }
        }
        private string _passwordSalt;
    
        [DataMember]
        public string Email
        {
            get { return _email; }
            set
            {
                if (_email != value)
                {
    				OnPropertyChanging("Email");
                    _email = value;
                    OnPropertyChanged("Email");
                }
            }
        }
        private string _email;
    
        [DataMember]
        public string PasswordQuestion
        {
            get { return _passwordQuestion; }
            set
            {
                if (_passwordQuestion != value)
                {
    				OnPropertyChanging("PasswordQuestion");
                    _passwordQuestion = value;
                    OnPropertyChanged("PasswordQuestion");
                }
            }
        }
        private string _passwordQuestion;
    
        [DataMember]
        public string PasswordAnswer
        {
            get { return _passwordAnswer; }
            set
            {
                if (_passwordAnswer != value)
                {
    				OnPropertyChanging("PasswordAnswer");
                    _passwordAnswer = value;
                    OnPropertyChanged("PasswordAnswer");
                }
            }
        }
        private string _passwordAnswer;
    
        [DataMember]
        public bool IsApproved
        {
            get { return _isApproved; }
            set
            {
                if (_isApproved != value)
                {
    				OnPropertyChanging("IsApproved");
                    _isApproved = value;
                    OnPropertyChanged("IsApproved");
                }
            }
        }
        private bool _isApproved;
    
        [DataMember]
        public bool IsLockedOut
        {
            get { return _isLockedOut; }
            set
            {
                if (_isLockedOut != value)
                {
    				OnPropertyChanging("IsLockedOut");
                    _isLockedOut = value;
                    OnPropertyChanged("IsLockedOut");
                }
            }
        }
        private bool _isLockedOut;
    
        [DataMember]
        public System.DateTime CreateDate
        {
            get { return _createDate; }
            set
            {
                if (_createDate != value)
                {
    				OnPropertyChanging("CreateDate");
                    _createDate = value;
                    OnPropertyChanged("CreateDate");
                }
            }
        }
        private System.DateTime _createDate;
    
        [DataMember]
        public System.DateTime LastLoginDate
        {
            get { return _lastLoginDate; }
            set
            {
                if (_lastLoginDate != value)
                {
    				OnPropertyChanging("LastLoginDate");
                    _lastLoginDate = value;
                    OnPropertyChanged("LastLoginDate");
                }
            }
        }
        private System.DateTime _lastLoginDate;
    
        [DataMember]
        public System.DateTime LastPasswordChangedDate
        {
            get { return _lastPasswordChangedDate; }
            set
            {
                if (_lastPasswordChangedDate != value)
                {
    				OnPropertyChanging("LastPasswordChangedDate");
                    _lastPasswordChangedDate = value;
                    OnPropertyChanged("LastPasswordChangedDate");
                }
            }
        }
        private System.DateTime _lastPasswordChangedDate;
    
        [DataMember]
        public System.DateTime LastLockoutDate
        {
            get { return _lastLockoutDate; }
            set
            {
                if (_lastLockoutDate != value)
                {
    				OnPropertyChanging("LastLockoutDate");
                    _lastLockoutDate = value;
                    OnPropertyChanged("LastLockoutDate");
                }
            }
        }
        private System.DateTime _lastLockoutDate;
    
        [DataMember]
        public int FailedPasswordAttemptCount
        {
            get { return _failedPasswordAttemptCount; }
            set
            {
                if (_failedPasswordAttemptCount != value)
                {
    				OnPropertyChanging("FailedPasswordAttemptCount");
                    _failedPasswordAttemptCount = value;
                    OnPropertyChanged("FailedPasswordAttemptCount");
                }
            }
        }
        private int _failedPasswordAttemptCount;
    
        [DataMember]
        public System.DateTime FailedPasswordAttemptWindowStart
        {
            get { return _failedPasswordAttemptWindowStart; }
            set
            {
                if (_failedPasswordAttemptWindowStart != value)
                {
    				OnPropertyChanging("FailedPasswordAttemptWindowStart");
                    _failedPasswordAttemptWindowStart = value;
                    OnPropertyChanged("FailedPasswordAttemptWindowStart");
                }
            }
        }
        private System.DateTime _failedPasswordAttemptWindowStart;
    
        [DataMember]
        public int FailedPasswordAnswerAttemptCount
        {
            get { return _failedPasswordAnswerAttemptCount; }
            set
            {
                if (_failedPasswordAnswerAttemptCount != value)
                {
    				OnPropertyChanging("FailedPasswordAnswerAttemptCount");
                    _failedPasswordAnswerAttemptCount = value;
                    OnPropertyChanged("FailedPasswordAnswerAttemptCount");
                }
            }
        }
        private int _failedPasswordAnswerAttemptCount;
    
        [DataMember]
        public System.DateTime FailedPasswordAnswerAttemptWindowsStart
        {
            get { return _failedPasswordAnswerAttemptWindowsStart; }
            set
            {
                if (_failedPasswordAnswerAttemptWindowsStart != value)
                {
    				OnPropertyChanging("FailedPasswordAnswerAttemptWindowsStart");
                    _failedPasswordAnswerAttemptWindowsStart = value;
                    OnPropertyChanged("FailedPasswordAnswerAttemptWindowsStart");
                }
            }
        }
        private System.DateTime _failedPasswordAnswerAttemptWindowsStart;
    
        [DataMember]
        public string Comment
        {
            get { return _comment; }
            set
            {
                if (_comment != value)
                {
    				OnPropertyChanging("Comment");
                    _comment = value;
                    OnPropertyChanged("Comment");
                }
            }
        }
        private string _comment;

        #endregion

        #region Navigation Properties
    
        [DataMember]
        public Applications Applications
        {
            get { return _applications; }
            set
            {
                if (!ReferenceEquals(_applications, value))
                {
                    var previousValue = _applications;
    				OnNavigationPropertyChanging("Applications");
                    _applications = value;
                    FixupApplications(previousValue);
                    OnNavigationPropertyChanged("Applications");
                }
            }
        }
        private Applications _applications;
    
        [DataMember]
        public Users Users
        {
            get { return _users; }
            set
            {
                if (!ReferenceEquals(_users, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added && value != null)
                    {
                        // This the dependent end of an identifying relationship, so the principal end cannot be changed if it is already set,
                        // otherwise it can only be set to an entity with a primary key that is the same value as the dependent's foreign key.
                        if (UserId != value.UserId)
                        {
                            throw new InvalidOperationException("The principal end of an identifying relationship can only be changed when the dependent end is in the Added state.");
                        }
                    }
                    var previousValue = _users;
    				OnNavigationPropertyChanging("Users");
                    _users = value;
                    FixupUsers(previousValue);
                    OnNavigationPropertyChanged("Users");
                }
            }
        }
        private Users _users;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
    	protected virtual void OnPropertyChanging(String propertyName)
        {
            if (_propertyChanging != null)
            {
                _propertyChanging(this, new PropertyChangingEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
    	protected virtual void OnNavigationPropertyChanging(String propertyName)
        {
            if (_propertyChanging != null)
            {
                _propertyChanging(this, new PropertyChangingEventArgs(propertyName));
            }
        }
    
    	public override bool Equals(System.Object obj)
    	{
    		// If parameter is null return false.
            if (obj == null)
            {
                return false;
            }
    
            // If parameter cannot be cast to Point return false.
            Memberships p = obj as Memberships;
            if ((System.Object)p == null)
            {
                return false;
            }
    
    			if (this.UserId != p.UserId)
    				return false;
    			if (this.ApplicationId != p.ApplicationId)
    				return false;
    			if (this.Password != p.Password)
    				return false;
    			if (this.PasswordFormat != p.PasswordFormat)
    				return false;
    			if (this.PasswordSalt != p.PasswordSalt)
    				return false;
    			if (this.Email != p.Email)
    				return false;
    			if (this.PasswordQuestion != p.PasswordQuestion)
    				return false;
    			if (this.PasswordAnswer != p.PasswordAnswer)
    				return false;
    			if (this.IsApproved != p.IsApproved)
    				return false;
    			if (this.IsLockedOut != p.IsLockedOut)
    				return false;
    			if (this.CreateDate != p.CreateDate)
    				return false;
    			if (this.LastLoginDate != p.LastLoginDate)
    				return false;
    			if (this.LastPasswordChangedDate != p.LastPasswordChangedDate)
    				return false;
    			if (this.LastLockoutDate != p.LastLockoutDate)
    				return false;
    			if (this.FailedPasswordAttemptCount != p.FailedPasswordAttemptCount)
    				return false;
    			if (this.FailedPasswordAttemptWindowStart != p.FailedPasswordAttemptWindowStart)
    				return false;
    			if (this.FailedPasswordAnswerAttemptCount != p.FailedPasswordAnswerAttemptCount)
    				return false;
    			if (this.FailedPasswordAnswerAttemptWindowsStart != p.FailedPasswordAnswerAttemptWindowsStart)
    				return false;
    			if (this.Comment != p.Comment)
    				return false;
    
    		return true;
    	}
    
    	public override int GetHashCode()
    	{
    		int hashCode = 1;
    			
    		hashCode ^= this.UserId.GetHashCode();
    			
    		hashCode ^= this.ApplicationId.GetHashCode();
    		if (this.Password != null)
    		{
    			hashCode ^= this.Password.GetHashCode();
    		}
    			
    		hashCode ^= this.PasswordFormat.GetHashCode();
    		if (this.PasswordSalt != null)
    		{
    			hashCode ^= this.PasswordSalt.GetHashCode();
    		}
    		if (this.Email != null)
    		{
    			hashCode ^= this.Email.GetHashCode();
    		}
    		if (this.PasswordQuestion != null)
    		{
    			hashCode ^= this.PasswordQuestion.GetHashCode();
    		}
    		if (this.PasswordAnswer != null)
    		{
    			hashCode ^= this.PasswordAnswer.GetHashCode();
    		}
    			
    		hashCode ^= this.IsApproved.GetHashCode();
    			
    		hashCode ^= this.IsLockedOut.GetHashCode();
    			
    		hashCode ^= this.CreateDate.GetHashCode();
    			
    		hashCode ^= this.LastLoginDate.GetHashCode();
    			
    		hashCode ^= this.LastPasswordChangedDate.GetHashCode();
    			
    		hashCode ^= this.LastLockoutDate.GetHashCode();
    			
    		hashCode ^= this.FailedPasswordAttemptCount.GetHashCode();
    			
    		hashCode ^= this.FailedPasswordAttemptWindowStart.GetHashCode();
    			
    		hashCode ^= this.FailedPasswordAnswerAttemptCount.GetHashCode();
    			
    		hashCode ^= this.FailedPasswordAnswerAttemptWindowsStart.GetHashCode();
    		if (this.Comment != null)
    		{
    			hashCode ^= this.Comment.GetHashCode();
    		}
    		return hashCode;
    	}
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        // This entity type is the dependent end in at least one association that performs cascade deletes.
        // This event handler will process notifications that occur when the principal end is deleted.
        internal void HandleCascadeDelete(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                this.MarkAsDeleted();
            }
        }
    
        protected virtual void ClearNavigationProperties()
        {
            Applications = null;
            Users = null;
        }

        #endregion

        #region Association Fixup
    
        private void FixupApplications(Applications previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.Memberships.Contains(this))
            {
                previousValue.Memberships.Remove(this);
            }
    
            if (Applications != null)
            {
                Applications.Memberships.Add(this);
    
                ApplicationId = Applications.ApplicationId;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("Applications")
                    && (ChangeTracker.OriginalValues["Applications"] == Applications))
                {
                    ChangeTracker.OriginalValues.Remove("Applications");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("Applications", previousValue);
                }
                if (Applications != null && !Applications.ChangeTracker.ChangeTrackingEnabled)
                {
                    Applications.StartTracking();
                }
            }
        }
    
        private void FixupUsers(Users previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && ReferenceEquals(previousValue.Memberships, this))
            {
                previousValue.Memberships = null;
            }
    
            if (Users != null)
            {
                Users.Memberships = this;
                UserId = Users.UserId;
            }
    
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("Users")
                    && (ChangeTracker.OriginalValues["Users"] == Users))
                {
                    ChangeTracker.OriginalValues.Remove("Users");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("Users", previousValue);
                }
                if (Users != null && !Users.ChangeTracker.ChangeTrackingEnabled)
                {
                    Users.StartTracking();
                }
            }
        }

        #endregion

    }
}
