//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FACCTS.Server.Model.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FACCTS_DBEntities1 : DbContext
    {
        public FACCTS_DBEntities1()
            : base("name=FACCTS_DBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ProfileData> ProfileData { get; set; }
        public DbSet<Profiles> Profiles { get; set; }
        public DbSet<Roles> Roles { get; set; }
        public DbSet<Sessions> Sessions { get; set; }
        public DbSet<Users> Users { get; set; }
        public DbSet<UsersInRoles> UsersInRoles { get; set; }
        public DbSet<Designations> Designations { get; set; }
        public DbSet<ParticipantRoles> ParticipantRoles { get; set; }
        public DbSet<Sex> Sex { get; set; }
        public DbSet<HairColors> HairColors { get; set; }
        public DbSet<EyeColors> EyeColors { get; set; }
        public DbSet<Races> Races { get; set; }
    }
}
