//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FACCTS.Server.Model.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OAuth_SymmetricCryptoKey
    {
        public string Bucket { get; set; }
        public string Handle { get; set; }
        public System.DateTime ExpiresUtc { get; set; }
        public byte[] Secret { get; set; }
    }
}
