//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FACCTS.Server.Model.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OAuth_ClientAuthorization
    {
        public System.Guid AuthorizationId { get; set; }
        public System.DateTime CreatedOnUtc { get; set; }
        public System.Guid ClientId { get; set; }
        public System.Guid UserId { get; set; }
        public string Scope { get; set; }
        public Nullable<System.DateTime> ExpirationDateUtc { get; set; }
    
        public virtual OAuth_Client OAuth_Client { get; set; }
        public virtual OAuth_Users OAuth_Users { get; set; }
    }
}
