//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FACCTS.Services.Integration.CCPOR_ResponseService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://isb.srv.courts-tc.ca.gov/portal/cajud/schema/ALL/DSP917CAJUDResp_Concrete" +
        "/1.0.0/wsdl", ConfigurationName="CCPOR_ResponseService.RestrainingOrderIssuanceCancelUpdateNotificationResponseSer" +
        "viceInterface")]
    public interface RestrainingOrderIssuanceCancelUpdateNotificationResponseServiceInterface {
        
        [System.ServiceModel.OperationContractAttribute(Action="/portal/cajud/Schema/DSP917CAJUDResp/1.0.0", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ReferenceType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MetadataType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AugmentationType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(@string))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComplexObjectType))]
        FACCTS.Services.Integration.CCPOR_ResponseService.NotifyResponse Notify(FACCTS.Services.Integration.CCPOR_ResponseService.NotifyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="/portal/cajud/Schema/DSP917CAJUDResp/1.0.0", ReplyAction="*")]
        System.Threading.Tasks.Task<FACCTS.Services.Integration.CCPOR_ResponseService.NotifyResponse> NotifyAsync(FACCTS.Services.Integration.CCPOR_ResponseService.NotifyRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://isb.srv.courts-tc.ca.gov/portal/cajud/Schema/DSP917CAJUDRespInput/2.0.0/xs" +
        "d")]
    public partial class DSP917CAJUDRespInput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ISBCommonServiceHeader iSBCommonServiceHeaderField;
        
        private ProductExchangePackageType productExchangePackageField;
        
        private AdditionalParams additionalParamsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="https://isb.srv.courts-tc.ca.gov/portal/isb/schema/ALL/ISBServices/CommonServices" +
            "/2.0.0", Order=0)]
        public ISBCommonServiceHeader ISBCommonServiceHeader {
            get {
                return this.iSBCommonServiceHeaderField;
            }
            set {
                this.iSBCommonServiceHeaderField = value;
                this.RaisePropertyChanged("ISBCommonServiceHeader");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="https://isb.srv.courts-tc.ca.gov/portal/cajud/schema/dsp917resp/2.0.0/xsd", Order=1)]
        public ProductExchangePackageType ProductExchangePackage {
            get {
                return this.productExchangePackageField;
            }
            set {
                this.productExchangePackageField = value;
                this.RaisePropertyChanged("ProductExchangePackage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="https://isb.srv.courts-tc.ca.gov/portal/isb/schema/ALL/ISBServices/CommonServices" +
            "/AdditionalParams/1.0.0", Order=2)]
        public AdditionalParams AdditionalParams {
            get {
                return this.additionalParamsField;
            }
            set {
                this.additionalParamsField = value;
                this.RaisePropertyChanged("AdditionalParams");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://isb.srv.courts-tc.ca.gov/portal/isb/schema/ALL/ISBServices/CommonServices" +
        "/2.0.0")]
    public partial class ISBCommonServiceHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sourceField;
        
        private string targetField;
        
        private string interfaceNameField;
        
        private string documentTypeField;
        
        private string documentIdField;
        
        private string correlationIdField;
        
        private string distributionIdField;
        
        private string iSBTransactionIdField;
        
        private string environmentField;
        
        private string hostnameField;
        
        private System.DateTime timeStampField;
        
        private string courtCdField;
        
        private string userIdField;
        
        private ISBCommonServiceHeaderRoutingInfo[] routingInfoField;
        
        private ISBCommonServiceHeaderSequencingInfo sequencingInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
                this.RaisePropertyChanged("Source");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Target {
            get {
                return this.targetField;
            }
            set {
                this.targetField = value;
                this.RaisePropertyChanged("Target");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string InterfaceName {
            get {
                return this.interfaceNameField;
            }
            set {
                this.interfaceNameField = value;
                this.RaisePropertyChanged("InterfaceName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string DocumentType {
            get {
                return this.documentTypeField;
            }
            set {
                this.documentTypeField = value;
                this.RaisePropertyChanged("DocumentType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string DocumentId {
            get {
                return this.documentIdField;
            }
            set {
                this.documentIdField = value;
                this.RaisePropertyChanged("DocumentId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string CorrelationId {
            get {
                return this.correlationIdField;
            }
            set {
                this.correlationIdField = value;
                this.RaisePropertyChanged("CorrelationId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string DistributionId {
            get {
                return this.distributionIdField;
            }
            set {
                this.distributionIdField = value;
                this.RaisePropertyChanged("DistributionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string ISBTransactionId {
            get {
                return this.iSBTransactionIdField;
            }
            set {
                this.iSBTransactionIdField = value;
                this.RaisePropertyChanged("ISBTransactionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string Environment {
            get {
                return this.environmentField;
            }
            set {
                this.environmentField = value;
                this.RaisePropertyChanged("Environment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string Hostname {
            get {
                return this.hostnameField;
            }
            set {
                this.hostnameField = value;
                this.RaisePropertyChanged("Hostname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public System.DateTime TimeStamp {
            get {
                return this.timeStampField;
            }
            set {
                this.timeStampField = value;
                this.RaisePropertyChanged("TimeStamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string CourtCd {
            get {
                return this.courtCdField;
            }
            set {
                this.courtCdField = value;
                this.RaisePropertyChanged("CourtCd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("UserId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RoutingInfo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public ISBCommonServiceHeaderRoutingInfo[] RoutingInfo {
            get {
                return this.routingInfoField;
            }
            set {
                this.routingInfoField = value;
                this.RaisePropertyChanged("RoutingInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public ISBCommonServiceHeaderSequencingInfo SequencingInfo {
            get {
                return this.sequencingInfoField;
            }
            set {
                this.sequencingInfoField = value;
                this.RaisePropertyChanged("SequencingInfo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://isb.srv.courts-tc.ca.gov/portal/isb/schema/ALL/ISBServices/CommonServices" +
        "/2.0.0")]
    public partial class ISBCommonServiceHeaderRoutingInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://niem.gov/niem/structures/2.0/CAJUD/CCMS/SendRestrainingOrderNotification-D" +
        "SP917/Response")]
    public partial class ReferenceType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string linkMetadataField;
        
        private string refField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, DataType="ID")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, DataType="IDREFS")]
        public string linkMetadata {
            get {
                return this.linkMetadataField;
            }
            set {
                this.linkMetadataField = value;
                this.RaisePropertyChanged("linkMetadata");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, DataType="IDREF")]
        public string @ref {
            get {
                return this.refField;
            }
            set {
                this.refField = value;
                this.RaisePropertyChanged("ref");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://niem.gov/niem/structures/2.0/CAJUD/CCMS/SendRestrainingOrderNotification-D" +
        "SP917/Response")]
    public abstract partial class MetadataType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, DataType="ID")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://niem.gov/niem/structures/2.0/CAJUD/CCMS/SendRestrainingOrderNotification-D" +
        "SP917/Response")]
    public abstract partial class AugmentationType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string metadataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, DataType="ID")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, DataType="IDREFS")]
        public string metadata {
            get {
                return this.metadataField;
            }
            set {
                this.metadataField = value;
                this.RaisePropertyChanged("metadata");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TextType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://niem.gov/niem/proxy/xsd/2.0/CAJUD/CCMS/SendRestrainingOrderNotification-DS" +
        "P917/Response")]
    public partial class @string : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string linkMetadataField;
        
        private string metadataField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://niem.gov/niem/structures/2.0/CAJUD/CCMS/SendRestrainingOrderNotification-D" +
            "SP917/Response", DataType="ID")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://niem.gov/niem/structures/2.0/CAJUD/CCMS/SendRestrainingOrderNotification-D" +
            "SP917/Response", DataType="IDREFS")]
        public string linkMetadata {
            get {
                return this.linkMetadataField;
            }
            set {
                this.linkMetadataField = value;
                this.RaisePropertyChanged("linkMetadata");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://niem.gov/niem/structures/2.0/CAJUD/CCMS/SendRestrainingOrderNotification-D" +
            "SP917/Response", DataType="IDREFS")]
        public string metadata {
            get {
                return this.metadataField;
            }
            set {
                this.metadataField = value;
                this.RaisePropertyChanged("metadata");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://niem.gov/niem/niem-core/2.0/CAJUD/CCMS/SendRestrainingOrderNotification-DS" +
        "P917/Response")]
    public partial class TextType : @string {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProductExchangeResponseActivityType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProductExchangePackageType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProductExchangeErrorActivityType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OrderIdentificationType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ErrorInformationType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CaseRestrainingOrderType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://niem.gov/niem/structures/2.0/CAJUD/CCMS/SendRestrainingOrderNotification-D" +
        "SP917/Response")]
    public abstract partial class ComplexObjectType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string linkMetadataField;
        
        private string metadataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, DataType="ID")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, DataType="IDREFS")]
        public string linkMetadata {
            get {
                return this.linkMetadataField;
            }
            set {
                this.linkMetadataField = value;
                this.RaisePropertyChanged("linkMetadata");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, DataType="IDREFS")]
        public string metadata {
            get {
                return this.metadataField;
            }
            set {
                this.metadataField = value;
                this.RaisePropertyChanged("metadata");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://isb.srv.courts-tc.ca.gov/portal/cajud/schema/dsp917resp/2.0.0/xsd")]
    public partial class ProductExchangeResponseActivityType : ComplexObjectType {
        
        private ControlNumber controlNumberField;
        
        private OrderIdentificationType orderIdentificationField;
        
        private CaseRestrainingOrderType caseRestrainingOrderField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ControlNumber ControlNumber {
            get {
                return this.controlNumberField;
            }
            set {
                this.controlNumberField = value;
                this.RaisePropertyChanged("ControlNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public OrderIdentificationType OrderIdentification {
            get {
                return this.orderIdentificationField;
            }
            set {
                this.orderIdentificationField = value;
                this.RaisePropertyChanged("OrderIdentification");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public CaseRestrainingOrderType CaseRestrainingOrder {
            get {
                return this.caseRestrainingOrderField;
            }
            set {
                this.caseRestrainingOrderField = value;
                this.RaisePropertyChanged("CaseRestrainingOrder");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://isb.srv.courts-tc.ca.gov/portal/cajud/schema/dsp917resp/2.0.0/xsd")]
    public partial class ControlNumber : TextType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://isb.srv.courts-tc.ca.gov/portal/cajud/schema/dsp917resp/2.0.0/xsd")]
    public partial class OrderIdentificationType : ComplexObjectType {
        
        private IdentificationID identificationIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://niem.gov/niem/niem-core/2.0/CAJUD/CCMS/SendRestrainingOrderNotification-DS" +
            "P917/Response", IsNullable=true, Order=0)]
        public IdentificationID IdentificationID {
            get {
                return this.identificationIDField;
            }
            set {
                this.identificationIDField = value;
                this.RaisePropertyChanged("IdentificationID");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://niem.gov/niem/niem-core/2.0/CAJUD/CCMS/SendRestrainingOrderNotification-DS" +
        "P917/Response")]
    public partial class IdentificationID : @string {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://isb.srv.courts-tc.ca.gov/portal/cajud/schema/dsp917resp/2.0.0/xsd")]
    public partial class CaseRestrainingOrderType : ComplexObjectType {
        
        private ActivityCategoryText activityCategoryTextField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://niem.gov/niem/niem-core/2.0/CAJUD/CCMS/SendRestrainingOrderNotification-DS" +
            "P917/Response", IsNullable=true, Order=0)]
        public ActivityCategoryText ActivityCategoryText {
            get {
                return this.activityCategoryTextField;
            }
            set {
                this.activityCategoryTextField = value;
                this.RaisePropertyChanged("ActivityCategoryText");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://niem.gov/niem/niem-core/2.0/CAJUD/CCMS/SendRestrainingOrderNotification-DS" +
        "P917/Response")]
    public partial class ActivityCategoryText : TextType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://isb.srv.courts-tc.ca.gov/portal/cajud/schema/dsp917resp/2.0.0/xsd")]
    public partial class ProductExchangePackageType : ComplexObjectType {
        
        private ComplexObjectType itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ProductExchangeErrorActivity", typeof(ProductExchangeErrorActivityType), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ProductExchangeResponseActivity", typeof(ProductExchangeResponseActivityType), Order=0)]
        public ComplexObjectType Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://isb.srv.courts-tc.ca.gov/portal/cajud/schema/dsp917resp/2.0.0/xsd")]
    public partial class ProductExchangeErrorActivityType : ComplexObjectType {
        
        private ErrorInformationType[] errorInformationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ErrorInformation", Order=0)]
        public ErrorInformationType[] ErrorInformation {
            get {
                return this.errorInformationField;
            }
            set {
                this.errorInformationField = value;
                this.RaisePropertyChanged("ErrorInformation");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://isb.srv.courts-tc.ca.gov/portal/cajud/schema/dsp917resp/2.0.0/xsd")]
    public partial class ErrorInformationType : ComplexObjectType {
        
        private ErrorInformationMessageCode errorInformationMessageCodeField;
        
        private ErrorInformationMessageText errorInformationMessageTextField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ErrorInformationMessageCode ErrorInformationMessageCode {
            get {
                return this.errorInformationMessageCodeField;
            }
            set {
                this.errorInformationMessageCodeField = value;
                this.RaisePropertyChanged("ErrorInformationMessageCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ErrorInformationMessageText ErrorInformationMessageText {
            get {
                return this.errorInformationMessageTextField;
            }
            set {
                this.errorInformationMessageTextField = value;
                this.RaisePropertyChanged("ErrorInformationMessageText");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://isb.srv.courts-tc.ca.gov/portal/cajud/schema/dsp917resp/2.0.0/xsd")]
    public partial class ErrorInformationMessageCode : TextType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://isb.srv.courts-tc.ca.gov/portal/cajud/schema/dsp917resp/2.0.0/xsd")]
    public partial class ErrorInformationMessageText : TextType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://isb.srv.courts-tc.ca.gov/portal/isb/schema/ALL/ISBServices/CommonServices" +
        "/2.0.0")]
    public partial class ISBCommonServiceHeaderSequencingInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string relatedSequenceIdField;
        
        private string groupIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string RelatedSequenceId {
            get {
                return this.relatedSequenceIdField;
            }
            set {
                this.relatedSequenceIdField = value;
                this.RaisePropertyChanged("RelatedSequenceId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string GroupId {
            get {
                return this.groupIdField;
            }
            set {
                this.groupIdField = value;
                this.RaisePropertyChanged("GroupId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://isb.srv.courts-tc.ca.gov/portal/isb/schema/ALL/ISBServices/CommonServices" +
        "/AdditionalParams/1.0.0")]
    public partial class AdditionalParams : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AdditionalParamsReplayParameters replayParametersField;
        
        private AdditionalParamsNVPairs[] nVPairsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AdditionalParamsReplayParameters ReplayParameters {
            get {
                return this.replayParametersField;
            }
            set {
                this.replayParametersField = value;
                this.RaisePropertyChanged("ReplayParameters");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NVPairs", Order=1)]
        public AdditionalParamsNVPairs[] NVPairs {
            get {
                return this.nVPairsField;
            }
            set {
                this.nVPairsField = value;
                this.RaisePropertyChanged("NVPairs");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://isb.srv.courts-tc.ca.gov/portal/isb/schema/ALL/ISBServices/CommonServices" +
        "/AdditionalParams/1.0.0")]
    public partial class AdditionalParamsReplayParameters : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tTLField;
        
        private string destinationField;
        
        private string maxReplayCountField;
        
        private AdditionalParamsReplayParametersReplaySchedule replayScheduleField;
        
        private AdditionalParamsReplayParametersCutOffSchedule cutOffScheduleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=0)]
        public string TTL {
            get {
                return this.tTLField;
            }
            set {
                this.tTLField = value;
                this.RaisePropertyChanged("TTL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
                this.RaisePropertyChanged("Destination");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=2)]
        public string MaxReplayCount {
            get {
                return this.maxReplayCountField;
            }
            set {
                this.maxReplayCountField = value;
                this.RaisePropertyChanged("MaxReplayCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public AdditionalParamsReplayParametersReplaySchedule ReplaySchedule {
            get {
                return this.replayScheduleField;
            }
            set {
                this.replayScheduleField = value;
                this.RaisePropertyChanged("ReplaySchedule");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public AdditionalParamsReplayParametersCutOffSchedule CutOffSchedule {
            get {
                return this.cutOffScheduleField;
            }
            set {
                this.cutOffScheduleField = value;
                this.RaisePropertyChanged("CutOffSchedule");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://isb.srv.courts-tc.ca.gov/portal/isb/schema/ALL/ISBServices/CommonServices" +
        "/AdditionalParams/1.0.0")]
    public partial class AdditionalParamsReplayParametersReplaySchedule : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ScheduleHMS scheduleHMSField;
        
        private System.DateTime scheduleDateTimeField;
        
        private bool scheduleDateTimeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ScheduleHMS ScheduleHMS {
            get {
                return this.scheduleHMSField;
            }
            set {
                this.scheduleHMSField = value;
                this.RaisePropertyChanged("ScheduleHMS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime ScheduleDateTime {
            get {
                return this.scheduleDateTimeField;
            }
            set {
                this.scheduleDateTimeField = value;
                this.RaisePropertyChanged("ScheduleDateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ScheduleDateTimeSpecified {
            get {
                return this.scheduleDateTimeFieldSpecified;
            }
            set {
                this.scheduleDateTimeFieldSpecified = value;
                this.RaisePropertyChanged("ScheduleDateTimeSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://isb.srv.courts-tc.ca.gov/portal/isb/schema/ALL/ISBServices/CommonServices" +
        "/AdditionalParams/1.0.0")]
    public partial class ScheduleHMS : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string hoursField;
        
        private string minutesField;
        
        private string secondsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=0)]
        public string Hours {
            get {
                return this.hoursField;
            }
            set {
                this.hoursField = value;
                this.RaisePropertyChanged("Hours");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=1)]
        public string Minutes {
            get {
                return this.minutesField;
            }
            set {
                this.minutesField = value;
                this.RaisePropertyChanged("Minutes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=2)]
        public string Seconds {
            get {
                return this.secondsField;
            }
            set {
                this.secondsField = value;
                this.RaisePropertyChanged("Seconds");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://isb.srv.courts-tc.ca.gov/portal/isb/schema/ALL/ISBServices/CommonServices" +
        "/AdditionalParams/1.0.0")]
    public partial class AdditionalParamsReplayParametersCutOffSchedule : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ScheduleHMS scheduleHMSField;
        
        private System.DateTime cutOffDateTimeField;
        
        private bool cutOffDateTimeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ScheduleHMS ScheduleHMS {
            get {
                return this.scheduleHMSField;
            }
            set {
                this.scheduleHMSField = value;
                this.RaisePropertyChanged("ScheduleHMS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime CutOffDateTime {
            get {
                return this.cutOffDateTimeField;
            }
            set {
                this.cutOffDateTimeField = value;
                this.RaisePropertyChanged("CutOffDateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CutOffDateTimeSpecified {
            get {
                return this.cutOffDateTimeFieldSpecified;
            }
            set {
                this.cutOffDateTimeFieldSpecified = value;
                this.RaisePropertyChanged("CutOffDateTimeSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://isb.srv.courts-tc.ca.gov/portal/isb/schema/ALL/ISBServices/CommonServices" +
        "/AdditionalParams/1.0.0")]
    public partial class AdditionalParamsNVPairs : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://isb.srv.courts-tc.ca.gov/portal/cajud/Schema/DSP917CAJUDRespOutput/1.0.0/x" +
        "sd")]
    public partial class DSP917CAJUDRespOutput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ISBCommonErrorMessage", typeof(ISBCommonErrorMessage), Namespace="https://isb.srv.courts-tc.ca.gov/portal/isb/schema/ALL/ISBServices/CommonServices" +
            "/Error/1.0.0", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ISBCommonResponseMessage", typeof(ISBCommonResponseMessage), Namespace="https://isb.srv.courts-tc.ca.gov/portal/isb/schema/ALL/ISBServices/CommonServices" +
            "/Response/1.0.0", Order=0)]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://isb.srv.courts-tc.ca.gov/portal/isb/schema/ALL/ISBServices/CommonServices" +
        "/Error/1.0.0")]
    public partial class ISBCommonErrorMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string exceptionCodeField;
        
        private string exceptionMessageField;
        
        private ISBCommonErrorMessageExceptionDetails[] exceptionDetailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ExceptionCode {
            get {
                return this.exceptionCodeField;
            }
            set {
                this.exceptionCodeField = value;
                this.RaisePropertyChanged("ExceptionCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ExceptionMessage {
            get {
                return this.exceptionMessageField;
            }
            set {
                this.exceptionMessageField = value;
                this.RaisePropertyChanged("ExceptionMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ExceptionDetails", Order=2)]
        public ISBCommonErrorMessageExceptionDetails[] ExceptionDetails {
            get {
                return this.exceptionDetailsField;
            }
            set {
                this.exceptionDetailsField = value;
                this.RaisePropertyChanged("ExceptionDetails");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://isb.srv.courts-tc.ca.gov/portal/isb/schema/ALL/ISBServices/CommonServices" +
        "/Error/1.0.0")]
    public partial class ISBCommonErrorMessageExceptionDetails : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string stackTraceField;
        
        private string msgField;
        
        private string fullClassField;
        
        private string classField;
        
        private object dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string StackTrace {
            get {
                return this.stackTraceField;
            }
            set {
                this.stackTraceField = value;
                this.RaisePropertyChanged("StackTrace");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Msg {
            get {
                return this.msgField;
            }
            set {
                this.msgField = value;
                this.RaisePropertyChanged("Msg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string FullClass {
            get {
                return this.fullClassField;
            }
            set {
                this.fullClassField = value;
                this.RaisePropertyChanged("FullClass");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Class {
            get {
                return this.classField;
            }
            set {
                this.classField = value;
                this.RaisePropertyChanged("Class");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public object Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("Data");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://isb.srv.courts-tc.ca.gov/portal/isb/schema/ALL/ISBServices/CommonServices" +
        "/Response/1.0.0")]
    public partial class ISBCommonResponseMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string statusField;
        
        private string messageField;
        
        private string documentIdField;
        
        private string correlationIdField;
        
        private string sequenceIdField;
        
        private string iSBTransactionIdField;
        
        private System.DateTime timeStampField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DocumentId {
            get {
                return this.documentIdField;
            }
            set {
                this.documentIdField = value;
                this.RaisePropertyChanged("DocumentId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string CorrelationId {
            get {
                return this.correlationIdField;
            }
            set {
                this.correlationIdField = value;
                this.RaisePropertyChanged("CorrelationId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string SequenceId {
            get {
                return this.sequenceIdField;
            }
            set {
                this.sequenceIdField = value;
                this.RaisePropertyChanged("SequenceId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ISBTransactionId {
            get {
                return this.iSBTransactionIdField;
            }
            set {
                this.iSBTransactionIdField = value;
                this.RaisePropertyChanged("ISBTransactionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public System.DateTime TimeStamp {
            get {
                return this.timeStampField;
            }
            set {
                this.timeStampField = value;
                this.RaisePropertyChanged("TimeStamp");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NotifyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://isb.srv.courts-tc.ca.gov/portal/cajud/Schema/DSP917CAJUDRespInput/2.0.0/xs" +
            "d", Order=0)]
        public FACCTS.Services.Integration.CCPOR_ResponseService.DSP917CAJUDRespInput DSP917CAJUDRespInput;
        
        public NotifyRequest() {
        }
        
        public NotifyRequest(FACCTS.Services.Integration.CCPOR_ResponseService.DSP917CAJUDRespInput DSP917CAJUDRespInput) {
            this.DSP917CAJUDRespInput = DSP917CAJUDRespInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NotifyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://isb.srv.courts-tc.ca.gov/portal/cajud/Schema/DSP917CAJUDRespOutput/1.0.0/x" +
            "sd", Order=0)]
        public FACCTS.Services.Integration.CCPOR_ResponseService.DSP917CAJUDRespOutput DSP917CAJUDRespOutput;
        
        public NotifyResponse() {
        }
        
        public NotifyResponse(FACCTS.Services.Integration.CCPOR_ResponseService.DSP917CAJUDRespOutput DSP917CAJUDRespOutput) {
            this.DSP917CAJUDRespOutput = DSP917CAJUDRespOutput;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RestrainingOrderIssuanceCancelUpdateNotificationResponseServiceInterfaceChannel : FACCTS.Services.Integration.CCPOR_ResponseService.RestrainingOrderIssuanceCancelUpdateNotificationResponseServiceInterface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RestrainingOrderIssuanceCancelUpdateNotificationResponseServiceInterfaceClient : System.ServiceModel.ClientBase<FACCTS.Services.Integration.CCPOR_ResponseService.RestrainingOrderIssuanceCancelUpdateNotificationResponseServiceInterface>, FACCTS.Services.Integration.CCPOR_ResponseService.RestrainingOrderIssuanceCancelUpdateNotificationResponseServiceInterface {
        
        public RestrainingOrderIssuanceCancelUpdateNotificationResponseServiceInterfaceClient() {
        }
        
        public RestrainingOrderIssuanceCancelUpdateNotificationResponseServiceInterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RestrainingOrderIssuanceCancelUpdateNotificationResponseServiceInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RestrainingOrderIssuanceCancelUpdateNotificationResponseServiceInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RestrainingOrderIssuanceCancelUpdateNotificationResponseServiceInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FACCTS.Services.Integration.CCPOR_ResponseService.NotifyResponse Notify(FACCTS.Services.Integration.CCPOR_ResponseService.NotifyRequest request) {
            return base.Channel.Notify(request);
        }
        
        public System.Threading.Tasks.Task<FACCTS.Services.Integration.CCPOR_ResponseService.NotifyResponse> NotifyAsync(FACCTS.Services.Integration.CCPOR_ResponseService.NotifyRequest request) {
            return base.Channel.NotifyAsync(request);
        }
    }
}
