#include "casesave.h"
#include "ui_casesave.h"
#include "qxmlputget.h"


casesave::casesave(QWidget *parent) :
    QDialog(parent),
    ui(new Ui::casesave)
{
    ui->setupUi(this);
}

casesave::~casesave()
{
    delete ui;
}

void casesave::setCase(QString caseId)
{
    ui->lineEdit_caseNumber->setText(caseId);
}


void casesave::LoadSaveFile()
{
    // GET CASE RECORD IN FULL
        QString listid;
        listid = ui->lineEdit_caseNumber->text();
        QStringList caseid;
        caseid << "/users/jamesreid/cases/" << listid << ".xml";
        QString savefile = caseid.join("");

        QString str100;
        QString str101;
        QString str102;
        QString str103;
        QString str104;
        QString str105;
        QString str106;
        QString str107;
        QString str108;
        QString str109;
        QString str110;
        QString str111;
        QString str112;
        QString str113;
        QString str114;
        QString str115;
        QString str116;
        QString str117;
        QString str118;
        QString str119;
        QString str120;
        QString str121;
        QString str122;
        QString str123;
        QString str124;
        QString str125;
        QString str126;
        QString str127;
        QString str128;
        QString str129;
        QString str130;
        QString str131;
        QString str132;
        QString str133;
        QString str134;
        QString str135;
        QString str136;
        QString str137;
        QString str138;
        QString str139;
        QString str140;
        QString str141;
        QString str142;
        QString str143;
        QString str144;
        QString str145;
        QString str146;
        QString str147;
        QString str148;
        QString str149;
        QString str150;
        QString str151;
        QString str152;
        QString str153;
        QString str154;
        QString str155;
        QString str156;
        QString str157;
        QString str158;
        QString str170;
        QString str171;
        QString str172;
        QString str173;
        QString str174;
        QString str175;
        QString str176;
        QString str177;
        QString str178;
        QString str179;
        QString str180;
        QString str181;
        QString str182;
        QString str183;
        QString str184;
        QString str185;
        QString str186;
        QString str187;
        QString str188;
        QString str189;
        QString str190;
        QString str191;
        QString str192;
        QString str193;
        QString str194;
        QString str195;
        QString str196;
        QString str197;
        QString str198;
        QString str199;
        QString str200;
        QString str201;
        QString str202;
        QString str203;
        QString str204;
        QString str205;
        QString str206;
        QString str207;
        QString str208;
        QString str209;
        QString str210;
        QString str211;
        QString str212;
        QString str213;
        QString str214;
        QString str215;
        QString str216;
        QString str217;
        QString str218;
        QString str219;
        QString str220;
        QString str221;
        QString str222;
        QString str223;
        QString str224;
        QString str225;
        QString str226;
        QString str227;
        QString str228;
        QString str229;
        QString str230;
        QString str231;
        QString str232;
        QString str233;
        QString str234;
        QString str235;
        QString str236;
        QString str237;
        QString str238;
        QString str239;
        QString str240;
        QString str241;
        QString str242;
        QString str243;
        QString str244;
        QString str245;
        QString str246;
        QString str247;
        QString str248;
        QString str249;
        QString str250;
        QString str251;
        QString str252;
        QString str253;
        QString str254;
        QString str255;
        QString str256;
        QString str257;
        QString str258;
        QString str259;
        QString str260;
        QString str261;
        QString str262;
        QString str263;
        QString str264;
        QString str265;
        QString str266;
        QString str267;
        QString str268;
        QString str269;
        QString str270;
        QString str271;
        QString str272;
        QString str273;
        QString str274;
        QString str275;
        QString str276;
        QString str277;
        QString str278;
        QString str279;
        QString str280;
        QString str281;
        QString str282;
        QString str283;
        QString str284;
        QString str285;
        QString str286;
        QString str287;
        QString str288;
        QString str289;

        QString str300;
        QString str301;
        QString str302;
        QString str303;
        QString str304;
        QString str305;
        QString str306;
        QString str307;
        QString str308;
        QString str309;
        QString str310;
        QString str311;
        QString str312;
        QString str313;
        QString str314;
        QString str315;
        QString str316;
        QString str317;
        QString str318;
        QString str319;
        QString str320;
        QString str321;

        int a, b, c, d, e, f, g, h, j, k, i, l, m, n, o ,p;

        QXmlGet xmlGet;
        xmlGet.load("/users/jamesreid/cases/tempsave.xml");

        xmlGet.find("caserecord");
        xmlGet.find("caseheader");
        xmlGet.descend();
        xmlGet.find("caseNumber");
        str154 = xmlGet.getString();
        xmlGet.find("caseFileDate");
        str155 = xmlGet.getString();
        xmlGet.find("caseStatus");
        str156 = xmlGet.getString();
        xmlGet.rise();
        xmlGet.find("parties");
        xmlGet.descend();
        xmlGet.find("party1");
        xmlGet.descend();
    //Party 1
        xmlGet.find("p1FirstName");
        str100 = xmlGet.getString();
        xmlGet.find("p1MiddleName");
        str101 = xmlGet.getString();
        xmlGet.find("p1LastName");
        str102 = xmlGet.getString();
        xmlGet.find("p1Role");
        a = xmlGet.getInt();
        xmlGet.find("p1Designation");
        b = xmlGet.getInt();
        xmlGet.find("p1Description");
        str103 = xmlGet.getString();
        xmlGet.find("p1Relationship");
        c = xmlGet.getInt();
        xmlGet.find("p1Hair");
        d = xmlGet.getInt();
        xmlGet.find("p1Eyes");
        e = xmlGet.getInt();
        xmlGet.find("p1Sex");
        f = xmlGet.getInt();
        xmlGet.find("p1Race");
        g = xmlGet.getInt();
        xmlGet.find("p1Age");
        str104 = xmlGet.getString();
        xmlGet.find("p1Parentrole");
        h = xmlGet.getInt();
        xmlGet.find("p1Weight");
        str105 = xmlGet.getString();
        xmlGet.find("p1HeightFeet");
        str106 = xmlGet.getString();
        xmlGet.find("p1HeightInch");
        str107 = xmlGet.getString();
        xmlGet.find("p1DOB");
        str108 = xmlGet.getString();
        xmlGet.find("p1AddressStreet");
        str109 = xmlGet.getString();
        xmlGet.find("p1AddressCity");
        str110 = xmlGet.getString();
        xmlGet.find("p1AddressState");
        str111 = xmlGet.getString();
        xmlGet.find("p1AddressPostal");
        str112 = xmlGet.getString();
        xmlGet.find("p1Phone");
        str113 = xmlGet.getString();
        xmlGet.find("p1Fax");
        str114 = xmlGet.getString();
        xmlGet.find("p1Email");
        str115 = xmlGet.getString();
    //P1 Attorney Info
        xmlGet.find("p1ProPer");
        bool p1ProPer = xmlGet.getBool();
        xmlGet.find("p1Attorney");
        bool p1Attorney = xmlGet.getBool();
        xmlGet.find("p1AttorneyFirstName");
        str116 = xmlGet.getString();
        xmlGet.find("p1AttorneyLastName");
        str117 = xmlGet.getString();
        xmlGet.find("p1AttorneyBarID");
        str118 = xmlGet.getString();
        xmlGet.find("p1AttorneyFirmName");
        str119 = xmlGet.getString();
        xmlGet.find("p1AttorneyAddressStreet");
        str120 = xmlGet.getString();
        xmlGet.find("p1AttorneyAddressCity");
        str121 = xmlGet.getString();
        xmlGet.find("p1AttorneyAddressState");
        str122 = xmlGet.getString();
        xmlGet.find("p1AttorneyAddressPostal");
        str123 = xmlGet.getString();
        xmlGet.find("p1AttorneyPhone");
        str124 = xmlGet.getString();
        xmlGet.find("p1AttorneyFax");
        str125 = xmlGet.getString();
        xmlGet.find("p1AttorneyEmail");
        str126 = xmlGet.getString();
        xmlGet.rise();
    //Party 2
        xmlGet.find("party2");
        xmlGet.descend();
        xmlGet.find("p2FirstName");
        str127 = xmlGet.getString();
        xmlGet.find("p2MiddleName");
        str128 = xmlGet.getString();
        xmlGet.find("p2LastName");
        str129 = xmlGet.getString();
        xmlGet.find("p2Role");
        i = xmlGet.getInt();
        xmlGet.find("p2Designation");
        j = xmlGet.getInt();
        xmlGet.find("p2Description");
        str130 = xmlGet.getString();
        xmlGet.find("p2Relationship");
        k = xmlGet.getInt();
        xmlGet.find("p2Hair");
        l = xmlGet.getInt();
        xmlGet.find("p2Eyes");
        m = xmlGet.getInt();
        xmlGet.find("p2Sex");
        n = xmlGet.getInt();
        xmlGet.find("p2Race");
        o = xmlGet.getInt();
        xmlGet.find("p2Age");
        str131 = xmlGet.getString();
        xmlGet.find("p2Parentrole");
        p = xmlGet.getInt();
        xmlGet.find("p2Weight");
        str132 = xmlGet.getString();
        xmlGet.find("p2HeightFeet");
        str133 = xmlGet.getString();
        xmlGet.find("p2HeightInch");
        str134 = xmlGet.getString();
        xmlGet.find("p2DOB");
        str135 = xmlGet.getString();
        xmlGet.find("p2AddressStreet");
        str136 = xmlGet.getString();
        xmlGet.find("p2AddressCity");
        str137 = xmlGet.getString();
        xmlGet.find("p2AddressState");
        str138 = xmlGet.getString();
        xmlGet.find("p2AddressPostal");
        str139 = xmlGet.getString();
        xmlGet.find("p2Phone");
        str140 = xmlGet.getString();
        xmlGet.find("p2Fax");
        str141 = xmlGet.getString();
        xmlGet.find("p2Email");
        str142 = xmlGet.getString();
    //P2 Attorney Info
        xmlGet.find("p2ProPer");
        bool p2ProPer = xmlGet.getBool();
        xmlGet.find("p2Attorney");
        bool p2Attorney = xmlGet.getBool();
        xmlGet.find("p2AttorneyFirstName");
        str143 = xmlGet.getString();
        xmlGet.find("p2AttorneyLastName");
        str144 = xmlGet.getString();
        xmlGet.find("p2AttorneyBarID");
        str145 = xmlGet.getString();
        xmlGet.find("p2AttorneyFirmName");
        str146 = xmlGet.getString();
        xmlGet.find("p2AttorneyAddressStreet");
        str147 = xmlGet.getString();
        xmlGet.find("p2AttorneyAddressCity");
        str148 = xmlGet.getString();
        xmlGet.find("p2AttorneyAddressState");
        str149 = xmlGet.getString();
        xmlGet.find("p2AttorneyAddressPostal");
        str150 = xmlGet.getString();
        xmlGet.find("p2AttorneyPhone");
        str151 = xmlGet.getString();
        xmlGet.find("p2AttorneyFax");
        str152 = xmlGet.getString();
        xmlGet.find("p2AttorneyEmail");
        str153 = xmlGet.getString();
        xmlGet.rise();
        xmlGet.find("party3");
        xmlGet.descend();
        xmlGet.find("p3ProPer");
        bool p3ProPer = xmlGet.getBool();
        xmlGet.find("p3AttorneyFirstName");
        str300 = xmlGet.getString();
        xmlGet.find("p3AttorneyLastName");
        str301 = xmlGet.getString();
        xmlGet.find("p3AttorneyBarID");
        str302 = xmlGet.getString();
        xmlGet.find("p3AttorneyFirmName");
        str303 = xmlGet.getString();
        xmlGet.find("p3AttorneyAddressStreet");
        str304 = xmlGet.getString();
        xmlGet.find("p3AttorneyAddressCity");
        str305 = xmlGet.getString();
        xmlGet.find("p3AttorneyAddressState");
        str306 = xmlGet.getString();
        xmlGet.find("p3AttorneyAddressPostal");
        str307= xmlGet.getString();
        xmlGet.find("p3AttorneyPhone");
        str308 = xmlGet.getString();
        xmlGet.find("p3AttorneyFax");
        str309 = xmlGet.getString();
        xmlGet.find("p3AttorneyEmail");
        str310 = xmlGet.getString();
        xmlGet.rise();
        xmlGet.find("childattorney");
        xmlGet.descend();
        xmlGet.find("c1AttorneyFirstName");
        str311 = xmlGet.getString();
        xmlGet.find("c1AttorneyLastName");
        str312 = xmlGet.getString();
        xmlGet.find("c1AttorneyBarID");
        str313 = xmlGet.getString();
        xmlGet.find("c1AttorneyFirmName");
        str314 = xmlGet.getString();
        xmlGet.find("c1AttorneyAddressStreet");
        str315 = xmlGet.getString();
        xmlGet.find("c1AttorneyAddressCity");
        str316 = xmlGet.getString();
        xmlGet.find("c1AttorneyAddressState");
        str317 = xmlGet.getString();
        xmlGet.find("c1AttorneyAddressPostal");
        str318= xmlGet.getString();
        xmlGet.find("c1AttorneyPhone");
        str319 = xmlGet.getString();
        xmlGet.find("c1AttorneyFax");
        str320 = xmlGet.getString();
        xmlGet.find("c1AttorneyEmail");
        str321 = xmlGet.getString();
        xmlGet.rise();



    //Children and Other Protected Table Data
        xmlGet.find("children");
        xmlGet.descend();
        xmlGet.find("child1");
        xmlGet.descend();
        xmlGet.find("entity");
        str170 = xmlGet.getString();
        xmlGet.find("firstname");
        str171 = xmlGet.getString();
        xmlGet.find("lastname");
        str172 = xmlGet.getString();
        xmlGet.find("relationship");
        str173 = xmlGet.getString();
        xmlGet.find("dateofbirth");
        str174 = xmlGet.getString();
        xmlGet.find("sex");
        str175 = xmlGet.getString();
        xmlGet.rise();
        xmlGet.find("child2");
        xmlGet.descend();
        xmlGet.findNext("entity");
        str176 = xmlGet.getString();
        xmlGet.findNext("firstname");
        str177 = xmlGet.getString();
        xmlGet.findNext("lastname");
        str178 = xmlGet.getString();
        xmlGet.findNext("relationship");
        str179 = xmlGet.getString();
        xmlGet.findNext("dateofbirth");
        str180 = xmlGet.getString();
        xmlGet.findNext("sex");
        str181 = xmlGet.getString();
        xmlGet.rise();
        xmlGet.rise();
        xmlGet.find("otherprotected");
        xmlGet.descend();
        xmlGet.find("otherprotected1");
        xmlGet.descend();
        xmlGet.find("entity");
        str182 = xmlGet.getString();
        xmlGet.find("firstname");
        str183 = xmlGet.getString();
        xmlGet.find("lastname");
        str184 = xmlGet.getString();
        xmlGet.find("relationship");
        str185 = xmlGet.getString();
        xmlGet.find("household");
        str186 = xmlGet.getString();
        xmlGet.find("sex");
        str187 = xmlGet.getString();
        xmlGet.rise();
        xmlGet.rise();
    //Other Entities
        xmlGet.find("witness");
        xmlGet.descend();
        xmlGet.find("witness1");
        xmlGet.descend();
        xmlGet.find("entity");
        str188 = xmlGet.getString();
        xmlGet.find("firstname");
        str189 = xmlGet.getString();
        xmlGet.find("lastname");
        str190 = xmlGet.getString();
        xmlGet.find("designation");
        str191 = xmlGet.getString();
        xmlGet.find("witnessfor");
        str192 = xmlGet.getString();
        xmlGet.find("contactinfo");
        str193 = xmlGet.getString();
        xmlGet.rise();
        xmlGet.find("witness2");
        xmlGet.descend();
        xmlGet.find("entity");
        str194 = xmlGet.getString();
        xmlGet.find("firstname");
        str195 = xmlGet.getString();
        xmlGet.find("lastname");
        str196 = xmlGet.getString();
        xmlGet.find("designation");
        str197 = xmlGet.getString();
        xmlGet.find("witnessfor");
        str198 = xmlGet.getString();
        xmlGet.find("contactinfo");
        str199 = xmlGet.getString();
        xmlGet.rise();
        xmlGet.rise();
        xmlGet.find("interpreter");
        xmlGet.descend();
        xmlGet.find("interpreter1");
        xmlGet.descend();
        xmlGet.find("entity");
        str200 = xmlGet.getString();
        xmlGet.find("firstname");
        str201 = xmlGet.getString();
        xmlGet.find("lastname");
        str202 = xmlGet.getString();
        xmlGet.find("designation");
        str203 = xmlGet.getString();
        xmlGet.find("interpreterfor");
        str204 = xmlGet.getString();
        xmlGet.find("language");
        str205 = xmlGet.getString();
        xmlGet.rise();
        xmlGet.rise();
        xmlGet.rise();
    //Related Cases
        xmlGet.find("relatedcases");
        xmlGet.descend();
        xmlGet.find("case1");
        xmlGet.descend();
        xmlGet.find("casenumber");
        str206 = xmlGet.getString();
        xmlGet.find("casetype");
        str207 = xmlGet.getString();
        xmlGet.find("county");
        str208 = xmlGet.getString();
        xmlGet.find("CPOTRO");
        str209 = xmlGet.getString();
        xmlGet.find("expirationdate");
        str210 = xmlGet.getString();
        xmlGet.find("leadcase");
        str211 = xmlGet.getString();
        xmlGet.rise();
        xmlGet.find("case2");
        xmlGet.descend();
        xmlGet.find("casenumber");
        str212 = xmlGet.getString();
        xmlGet.find("casetype");
        str213 = xmlGet.getString();
        xmlGet.find("county");
        str214 = xmlGet.getString();
        xmlGet.find("CPOTRO");
        str215 = xmlGet.getString();
        xmlGet.find("expirationdate");
        str216 = xmlGet.getString();
        xmlGet.find("leadcase");
        str217 = xmlGet.getString();
        xmlGet.rise();
        xmlGet.find("case3");
        xmlGet.descend();
        xmlGet.find("casenumber");
        str218 = xmlGet.getString();
        xmlGet.find("casetype");
        str219 = xmlGet.getString();
        xmlGet.find("county");
        str220 = xmlGet.getString();
        xmlGet.find("CPOTRO");
        str221 = xmlGet.getString();
        xmlGet.find("expirationdate");
        str222 = xmlGet.getString();
        xmlGet.find("leadcase");
        str223 = xmlGet.getString();
        xmlGet.rise();
        xmlGet.rise();
    //Get History
        xmlGet.find("casehistory");
        xmlGet.descend();
        xmlGet.find("event1");
        xmlGet.descend();
        xmlGet.find("date");
        str224 = xmlGet.getString();
        xmlGet.find("event");
        str225 = xmlGet.getString();
        xmlGet.find("party1present");
        str226 = xmlGet.getString();
        xmlGet.find("party1sworn");
        str227 = xmlGet.getString();
        xmlGet.find("party1atty");
        str228 = xmlGet.getString();
        xmlGet.find("party2present");
        str229 = xmlGet.getString();
        xmlGet.find("party2sworn");
        str230 = xmlGet.getString();
        xmlGet.find("party2atty");
        str231 = xmlGet.getString();
        xmlGet.find("orders");
        str232 = xmlGet.getString();
        xmlGet.find("mergedCase");
        str233 = xmlGet.getString();
        xmlGet.rise();
        xmlGet.find("event2");
        xmlGet.descend();
        xmlGet.findNext("date");
        str234 = xmlGet.getString();
        xmlGet.findNext("event");
        str235 = xmlGet.getString();
        xmlGet.findNext("party1present");
        str236 = xmlGet.getString();
        xmlGet.findNext("party1sworn");
        str237 = xmlGet.getString();
        xmlGet.findNext("party1atty");
        str238 = xmlGet.getString();
        xmlGet.findNext("party2present");
        str239 = xmlGet.getString();
        xmlGet.findNext("party2sworn");
        str240 = xmlGet.getString();
        xmlGet.findNext("party2atty");
        str241 = xmlGet.getString();
        xmlGet.findNext("orders");
        str242 = xmlGet.getString();
        xmlGet.findNext("mergedCase");
        str243 = xmlGet.getString();
        xmlGet.rise();
        xmlGet.find("event3");
        xmlGet.descend();
        xmlGet.find("date");
        str244 = xmlGet.getString();
        xmlGet.find("event");
        str245 = xmlGet.getString();
        xmlGet.find("party1present");
        str246 = xmlGet.getString();
        xmlGet.find("party1sworn");
        str247 = xmlGet.getString();
        xmlGet.find("party1atty");
        str248 = xmlGet.getString();
        xmlGet.find("party2present");
        str249 = xmlGet.getString();
        xmlGet.find("party2sworn");
        str250 = xmlGet.getString();
        xmlGet.find("party2atty");
        str251 = xmlGet.getString();
        xmlGet.find("orders");
        str252 = xmlGet.getString();
        xmlGet.find("mergedCase");
        str253 = xmlGet.getString();
        xmlGet.rise();
        xmlGet.find("event4");
        xmlGet.descend();
        xmlGet.find("date");
        str254 = xmlGet.getString();
        xmlGet.find("event");
        str255 = xmlGet.getString();
        xmlGet.find("party1present");
        str256 = xmlGet.getString();
        xmlGet.find("party1sworn");
        str257 = xmlGet.getString();
        xmlGet.find("party1atty");
        str258 = xmlGet.getString();
        xmlGet.find("party2present");
        str259 = xmlGet.getString();
        xmlGet.find("party2sworn");
        str260 = xmlGet.getString();
        xmlGet.find("party2atty");
        str261 = xmlGet.getString();
        xmlGet.find("orders");
        str262 = xmlGet.getString();
        xmlGet.find("mergedCase");
        str263 = xmlGet.getString();
        xmlGet.rise();
        xmlGet.find("event5");
        xmlGet.descend();
        xmlGet.find("date");
        str264 = xmlGet.getString();
        xmlGet.find("event");
        str265 = xmlGet.getString();
        xmlGet.find("party1present");
        str266 = xmlGet.getString();
        xmlGet.find("party1sworn");
        str267 = xmlGet.getString();
        xmlGet.find("party1atty");
        str268 = xmlGet.getString();
        xmlGet.find("party2present");
        str269 = xmlGet.getString();
        xmlGet.find("party2sworn");
        str270 = xmlGet.getString();
        xmlGet.find("party2atty");
        str271 = xmlGet.getString();
        xmlGet.find("orders");
        str272 = xmlGet.getString();
        xmlGet.find("mergedCase");
        str273 = xmlGet.getString();
        xmlGet.rise();
        xmlGet.rise();
    //Case Notes
        xmlGet.find("casenotes");
        xmlGet.descend();
        xmlGet.find("user1");
        xmlGet.descend();
        xmlGet.find("userid");
        str274 = xmlGet.getString();
        xmlGet.find("userrole");
        str275 = xmlGet.getString();
        xmlGet.find("lastdate");
        str276 = xmlGet.getString();
        xmlGet.find("publicnotes");
        str277 = xmlGet.getString();
        xmlGet.rise();
        xmlGet.find("user2");
        xmlGet.descend();
        xmlGet.find("userid");
        str278 = xmlGet.getString();
        xmlGet.find("userrole");
        str279 = xmlGet.getString();
        xmlGet.find("lastdate");
        str280 = xmlGet.getString();
        xmlGet.find("publicnotes");
        str281 = xmlGet.getString();
        xmlGet.rise();
        xmlGet.find("user3");
        xmlGet.descend();
        xmlGet.find("userid");
        str282 = xmlGet.getString();
        xmlGet.find("userrole");
        str283 = xmlGet.getString();
        xmlGet.find("lastdate");
        str284 = xmlGet.getString();
        xmlGet.find("publicnotes");
        str285 = xmlGet.getString();
        xmlGet.rise();
        xmlGet.find("user4");
        xmlGet.descend();
        xmlGet.findNext("userid");
        str286 = xmlGet.getString();
        xmlGet.findNext("userrole");
        str287 = xmlGet.getString();
        xmlGet.findNext("lastdate");
        str288 = xmlGet.getString();
        xmlGet.findNext("publicnotes");
        str289 = xmlGet.getString();
        xmlGet.rise();
        xmlGet.rise();



// SAVE CASE RECORD IN FULL


        QXmlPut xmlPut("caserecord");

    //put caseHeader
        xmlPut.descend("caseheader");
        xmlPut.putString("caseNumber", str154);
        xmlPut.putString("caseFileDate", str155);
        xmlPut.putString("caseStatus", str156);
        xmlPut.rise();
        xmlPut.descend("parties");
    //put party 1
        xmlPut.descend("party1");
        xmlPut.putString("p1FirstName", str100);
        xmlPut.putString("p1MiddleName", str101);
        xmlPut.putString("p1LastName", str102);
        xmlPut.putInt("p1Role", a);
        xmlPut.putInt("p1Designation", b);
        xmlPut.putString("p1Description", str103);
        xmlPut.putInt("p1Relationship", c);
        xmlPut.putInt("p1Hair", d);
        xmlPut.putInt("p1Eyes", e);
        xmlPut.putInt("p1Sex", f);
        xmlPut.putInt("p1Race", g);
        xmlPut.putString("p1Age", str104);
        xmlPut.putInt("p1Parentrole", h);
        xmlPut.putString("p1Weight", str105);
        xmlPut.putString("p1HeightFeet", str106);
        xmlPut.putString("p1HeightInch", str107);
        xmlPut.putString("p1DOB", str108);
        xmlPut.putString("p1AddressStreet", str109);
        xmlPut.putString("p1AddressCity", str110);
        xmlPut.putString("p1AddressState", str111);
        xmlPut.putString("p1AddressPostal", str112);
        xmlPut.putString("p1Phone", str113);
        xmlPut.putString("p1Fax", str114);
        xmlPut.putString("p1Email", str115);
        xmlPut.putBool("p1ProPer", p1ProPer);
        xmlPut.putBool("p1Attorney", p1Attorney);
        xmlPut.putString("p1AttorneyFirstName", str116);
        xmlPut.putString("p1AttorneyLastName", str117);
        xmlPut.putString("p1AttorneyBarID", str118);
        xmlPut.putString("p1AttorneyFirmName", str119);
        xmlPut.putString("p1AttorneyAddressStreet", str120);
        xmlPut.putString("p1AttorneyAddressCity", str121);
        xmlPut.putString("p1AttorneyAddressState", str122);
        xmlPut.putString("p1AttorneyAddressPostal", str123);
        xmlPut.putString("p1AttorneyPhone", str124);
        xmlPut.putString("p1AttorneyFax", str125);
        xmlPut.putString("p1AttorneyEmail", str126);

        xmlPut.rise();
    //put party 2
        xmlPut.descend("party2");
        xmlPut.putString("p2FirstName", str127);
        xmlPut.putString("p2MiddleName", str128);
        xmlPut.putString("p2LastName", str129);
        xmlPut.putInt("p2Role", i);
        xmlPut.putInt("p2Designation", j);
        xmlPut.putString("p2Description", str130);
        xmlPut.putInt("p2Relationship", k);
        xmlPut.putInt("p2Hair", l);
        xmlPut.putInt("p2Eyes", m);
        xmlPut.putInt("p2Sex", n);
        xmlPut.putInt("p2Race", o);
        xmlPut.putString("p2Age", str131);
        xmlPut.putInt("p2Parentrole", p);
        xmlPut.putString("p2Weight", str132);
        xmlPut.putString("p2HeightFeet", str133);
        xmlPut.putString("p2HeightInch", str134);
        xmlPut.putString("p2DOB", str135);
        xmlPut.putString("p2AddressStreet", str136);
        xmlPut.putString("p2AddressCity", str137);
        xmlPut.putString("p2AddressState", str138);
        xmlPut.putString("p2AddressPostal", str139);
        xmlPut.putString("p2Phone", str140);
        xmlPut.putString("p2Fax", str141);
        xmlPut.putString("p2Email", str142);
        xmlPut.putBool("p2ProPer", p2ProPer);
        xmlPut.putBool("p2Attorney", p2Attorney);
        xmlPut.putString("p2AttorneyFirstName", str143);
        xmlPut.putString("p2AttorneyLastName", str144);
        xmlPut.putString("p2AttorneyBarID", str145);
        xmlPut.putString("p2AttorneyFirmName", str146);
        xmlPut.putString("p2AttorneyAddressStreet", str147);
        xmlPut.putString("p2AttorneyAddressCity", str148);
        xmlPut.putString("p2AttorneyAddressState", str149);
        xmlPut.putString("p2AttorneyAddressPostal", str150);
        xmlPut.putString("p2AttorneyPhone", str151);
        xmlPut.putString("p2AttorneyFax", str152);
        xmlPut.putString("p2AttorneyEmail", str153);
        xmlPut.rise();
        xmlPut.descend("party3");
        xmlPut.putBool("p3ProPer", p3ProPer);
        xmlPut.putString("p3AttorneyFirstName", str300);
        xmlPut.putString("p3AttorneyLastName", str301);
        xmlPut.putString("p3AttorneyBarID", str302);
        xmlPut.putString("p3AttorneyFirmName", str303);
        xmlPut.putString("p3AttorneyAddressStreet", str304);
        xmlPut.putString("p3AttorneyAddressCity", str305);
        xmlPut.putString("p3AttorneyAddressState", str306);
        xmlPut.putString("p3AttorneyAddressPostal", str307);
        xmlPut.putString("p3AttorneyPhone", str308);
        xmlPut.putString("p3AttorneyFax", str309);
        xmlPut.putString("p3AttorneyEmail", str310);
        xmlPut.rise();
        xmlPut.descend("childattorney");
        xmlPut.putString("c1AttorneyFirstName", str311);
        xmlPut.putString("c1AttorneyLastName", str312);
        xmlPut.putString("c1AttorneyBarID", str313);
        xmlPut.putString("c1AttorneyFirmName", str314);
        xmlPut.putString("c1AttorneyAddressStreet", str315);
        xmlPut.putString("c1AttorneyAddressCity", str316);
        xmlPut.putString("c1AttorneyAddressState", str317);
        xmlPut.putString("c1AttorneyAddressPostal", str318);
        xmlPut.putString("c1AttorneyPhone", str319);
        xmlPut.putString("c1AttorneyFax", str320);
        xmlPut.putString("c1AttorneyEmail", str321);
        xmlPut.rise();
        xmlPut.descend("children");
        xmlPut.descend("child1");
        xmlPut.putString("entity", str170);
        xmlPut.putString("firstname", str171);
        xmlPut.putString("lastname", str172);
        xmlPut.putString("relationship", str173);
        xmlPut.putString("dateofbirth", str174);
        xmlPut.putString("sex", str175);
        xmlPut.rise();
        xmlPut.descend("child2");
        xmlPut.putString("entity", str176);
        xmlPut.putString("firstname", str177);
        xmlPut.putString("lastname", str178);
        xmlPut.putString("relationship", str179);
        xmlPut.putString("dateofbirth", str180);
        xmlPut.putString("sex", str181);
        xmlPut.rise();
        xmlPut.rise();
        xmlPut.descend("otherprotected");
        xmlPut.descend("otherprotected1");
        xmlPut.putString("entity", str182);
        xmlPut.putString("firstname", str183);
        xmlPut.putString("lastname", str184);
        xmlPut.putString("relationship", str185);
        xmlPut.putString("household", str186);
        xmlPut.putString("sex", str187);
        xmlPut.rise();
        xmlPut.rise();
        xmlPut.descend("witness");
        xmlPut.descend("witness1");
        xmlPut.putString("entity", str188);
        xmlPut.putString("firstname", str189);
        xmlPut.putString("lastname", str190);
        xmlPut.putString("designation", str191);
        xmlPut.putString("witnessfor", str192);
        xmlPut.putString("contactinfo", str193);
        xmlPut.rise();
        xmlPut.descend("witness2");
        xmlPut.putString("entity", str194);
        xmlPut.putString("firstname", str195);
        xmlPut.putString("lastname", str196);
        xmlPut.putString("designation", str197);
        xmlPut.putString("witnessfor", str198);
        xmlPut.putString("contactinfo", str199);
        xmlPut.rise();
        xmlPut.rise();
        xmlPut.descend("interpreter");
        xmlPut.descend("interpreter1");
        xmlPut.putString("entity", str200);
        xmlPut.putString("firstname", str201);
        xmlPut.putString("lastname", str202);
        xmlPut.putString("designation", str203);
        xmlPut.putString("interpreterfor", str204);
        xmlPut.putString("language", str205);
        xmlPut.rise();
        xmlPut.rise();
        xmlPut.rise();
        xmlPut.descend("relatedcases");
        xmlPut.descend("case1");
        xmlPut.putString("casenumber", str206);
        xmlPut.putString("casetype", str207);
        xmlPut.putString("county", str208);
        xmlPut.putString("CPOTRO", str209);
        xmlPut.putString("expirationdate", str210);
        xmlPut.putString("leadcase", str211);
        xmlPut.rise();
        xmlPut.descend("case2");
        xmlPut.putString("casenumber", str212);
        xmlPut.putString("casetype", str213);
        xmlPut.putString("county", str214);
        xmlPut.putString("CPOTRO", str215);
        xmlPut.putString("expirationdate", str216);
        xmlPut.putString("leadcase", str217);
        xmlPut.rise();
        xmlPut.descend("case3");
        xmlPut.putString("casenumber", str218);
        xmlPut.putString("casetype", str219);
        xmlPut.putString("county", str220);
        xmlPut.putString("CPOTRO", str221);
        xmlPut.putString("expirationdate", str222);
        xmlPut.putString("leadcase", str223);
        xmlPut.rise();
        xmlPut.rise();
        xmlPut.descend("casehistory");
        xmlPut.descend("event1");
        xmlPut.putString("date", str224);
        xmlPut.putString("event", str225);
        xmlPut.putString("party1present", str226);
        xmlPut.putString("party1sworn", str227);
        xmlPut.putString("party1atty", str228);
        xmlPut.putString("party2present", str229);
        xmlPut.putString("party2sworn", str230);
        xmlPut.putString("party2atty", str231);
        xmlPut.putString("orders", str232);
        xmlPut.putString("mergedCase", str233);
        xmlPut.rise();
        xmlPut.descend("event2");
        xmlPut.putString("date", str234);
        xmlPut.putString("event", str235);
        xmlPut.putString("party1present", str236);
        xmlPut.putString("party1sworn", str237);
        xmlPut.putString("party1atty", str238);
        xmlPut.putString("party2present", str239);
        xmlPut.putString("party2sworn", str240);
        xmlPut.putString("party2atty", str241);
        xmlPut.putString("orders", str242);
        xmlPut.putString("mergedCase", str243);
        xmlPut.rise();
        xmlPut.descend("event3");
        xmlPut.putString("date", str244);
        xmlPut.putString("event", str245);
        xmlPut.putString("party1present", str246);
        xmlPut.putString("party1sworn", str247);
        xmlPut.putString("party1atty", str248);
        xmlPut.putString("party2present", str249);
        xmlPut.putString("party2sworn", str250);
        xmlPut.putString("party2atty", str251);
        xmlPut.putString("orders", str252);
        xmlPut.putString("mergedCase", str253);
        xmlPut.rise();
        xmlPut.rise();
        xmlPut.descend("event4");
        xmlPut.putString("date", str254);
        xmlPut.putString("event", str255);
        xmlPut.putString("party1present", str256);
        xmlPut.putString("party1sworn", str257);
        xmlPut.putString("party1atty", str258);
        xmlPut.putString("party2present", str259);
        xmlPut.putString("party2sworn", str260);
        xmlPut.putString("party2atty", str261);
        xmlPut.putString("orders", str262);
        xmlPut.putString("mergedCase", str263);
        xmlPut.rise();
        xmlPut.descend("event5");
        xmlPut.putString("date", str264);
        xmlPut.putString("event", str265);
        xmlPut.putString("party1present", str266);
        xmlPut.putString("party1sworn", str267);
        xmlPut.putString("party1atty", str268);
        xmlPut.putString("party2present", str269);
        xmlPut.putString("party2sworn", str270);
        xmlPut.putString("party2atty", str271);
        xmlPut.putString("orders", str272);
        xmlPut.putString("mergedCase", str273);
        xmlPut.rise();
        xmlPut.rise();
        xmlPut.descend("casenotes");
        xmlPut.descend("user1");
        xmlPut.putString("userid", str274);
        xmlPut.putString("userrole", str275);
        xmlPut.putString("lastdate", str276);
        xmlPut.putString("publicnotes", str277);
        xmlPut.putString("privatenotes", "");
        xmlPut.rise();
        xmlPut.descend("user2");
        xmlPut.putString("userid", str278);
        xmlPut.putString("userrole", str279);
        xmlPut.putString("lastdate", str280);
        xmlPut.putString("publicnotes", str281);
        xmlPut.putString("privatenotes", "");
        xmlPut.rise();
        xmlPut.descend("user3");
        xmlPut.putString("userid", str282);
        xmlPut.putString("userrole", str283);
        xmlPut.putString("lastdate", str284);
        xmlPut.putString("publicnotes", str285);
        xmlPut.putString("privatenotes", "");
        xmlPut.rise();
        xmlPut.descend("user4");
        xmlPut.putString("userid", str286);
        xmlPut.putString("userrole", str287);
        xmlPut.putString("lastdate", str288);
        xmlPut.putString("publicnotes", str289);
        xmlPut.putString("privatenotes", "");
        xmlPut.rise();
        xmlPut.rise();
        xmlPut.rise();

    // write xml
        xmlPut.save(savefile);

}








void casesave::on_toolButton_saveRecord_clicked()
{
   //Execute LOAD SAVE
   LoadSaveFile();
   close();
}
